//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "baselines")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    /// この baseline が代表するブランチ。
    pub branch: String,
    /// 昇格元のビルド（削除されたら NULL に落とす）。
    pub source_build_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_build_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub builds: HasOne<super::builds::Entity>,
    #[sea_orm(has_many)]
    pub baseline_entries: HasMany<super::baseline_entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
