//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "baseline_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "baseline_entries_baseline_id_name_key")]
    pub baseline_id: Uuid,
    #[sea_orm(unique_key = "baseline_entries_baseline_id_name_key")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub width: i32,
    pub height: i32,
    #[sea_orm(
        belongs_to,
        from = "baseline_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub baselines: HasOne<super::baselines::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
