//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "builds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "builds_project_id_number_key")]
    pub project_id: Uuid,
    /// プロジェクト内で連番のビルド番号（`project_build_counters` が採番）。
    #[sea_orm(unique_key = "builds_project_id_number_key")]
    pub number: i64,
    pub branch: String,
    pub commit_sha: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_message: Option<String>,
    pub pull_request_number: Option<i32>,
    pub status: super::super::builds::BuildStatus,
    /// 入力形式（`screenshots` = CI が PNG を送る / `storybook` = サーバーが撮る）。
    pub mode: super::super::builds::BuildMode,
    /// storybook モードでアップロードされた zip のストレージキー。
    #[sea_orm(column_type = "Text", nullable)]
    pub storybook_key: Option<String>,
    /// 比較に使う baseline。部分撮影（capture plan / only_story_ids）が固定した
    /// ときだけ事前に埋まり、それ以外は比較ジョブが比較後に記録する
    /// （NULL = 未固定。比較時に最新を解決する従来動作）。
    /// FK にすると `baselines.source_build_id` と循環するため素のカラム。
    pub baseline_id: Option<Uuid>,
    /// screenshots モードの部分アップロード計画
    /// （`{"selected_names": [...], "manifest_names": [...]}`）。
    /// 撮影開始前に `POST /v1/ci/builds/{id}/plan` が書き込む。NULL は全撮影。
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub capture_plan: Option<Json>,
    pub total_count: i32,
    pub changed_count: i32,
    pub added_count: i32,
    pub removed_count: i32,
    pub unchanged_count: i32,
    /// content hash 一致により decode と diff を省略した比較数。
    pub content_hash_skipped_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub approval_evidence: Option<Json>,
    pub approved_by: Option<Uuid>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "approved_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
    #[sea_orm(has_many)]
    pub screenshots: HasMany<super::screenshots::Entity>,
    #[sea_orm(has_many)]
    pub comparisons: HasMany<super::comparisons::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
