//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "builds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "builds_project_id_number_key")]
    pub project_id: Uuid,
    /// プロジェクト内で連番のビルド番号（`project_build_counters` が採番）。
    #[sea_orm(unique_key = "builds_project_id_number_key")]
    pub number: i64,
    pub branch: String,
    pub commit_sha: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_message: Option<String>,
    pub pull_request_number: Option<i32>,
    pub status: super::super::builds::BuildStatus,
    /// 比較に使った baseline。FK にすると `baselines.source_build_id` と循環するため素のカラム。
    pub baseline_id: Option<Uuid>,
    pub total_count: i32,
    pub changed_count: i32,
    pub added_count: i32,
    pub removed_count: i32,
    pub unchanged_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub approved_by: Option<Uuid>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "approved_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
    #[sea_orm(has_many)]
    pub screenshots: HasMany<super::screenshots::Entity>,
    #[sea_orm(has_many)]
    pub comparisons: HasMany<super::comparisons::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
