//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "comparisons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "comparisons_build_id_name_key")]
    pub build_id: Uuid,
    #[sea_orm(unique_key = "comparisons_build_id_name_key")]
    pub name: String,
    /// 今回のスクリーンショット。`None` は baseline から消えた（removed）ことを意味する。
    pub screenshot_id: Option<Uuid>,
    /// 比較元の baseline エントリ。`None` は新規追加（added）。
    pub baseline_entry_id: Option<Uuid>,
    pub status: super::super::comparisons::ComparisonStatus,
    pub review_status: super::super::comparisons::ReviewStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub diff_storage_key: Option<String>,
    pub diff_pixel_count: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub diff_ratio: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub reviewed_by: Option<Uuid>,
    pub reviewed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "build_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub builds: HasOne<super::builds::Entity>,
    #[sea_orm(
        belongs_to,
        from = "screenshot_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub screenshots: HasOne<super::screenshots::Entity>,
    #[sea_orm(
        belongs_to,
        from = "baseline_entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub baseline_entries: HasOne<super::baseline_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "reviewed_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
