//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "github_installations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// claim されるまで `None`。webhook で作られた直後は宙に浮いた状態。
    pub tenant_id: Option<Uuid>,
    /// GitHub 側の installation ID。webhook の冪等な upsert キー。
    #[sea_orm(unique)]
    pub installation_id: i64,
    /// インストール先アカウント名（`octocat` / `acme-inc`）。
    #[sea_orm(column_type = "Text")]
    pub account_login: String,
    /// `User` | `Organization`。
    #[sea_orm(column_type = "Text")]
    pub account_type: String,
    /// GitHub 側で suspend されている間だけ値が入る。
    pub suspended_at: Option<DateTimeWithTimeZone>,
    /// アンインストール時に打つ論理削除。行は監査のため残す。
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
