//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod baseline_entries;
pub mod baselines;
pub mod build_logs;
pub mod builds;
pub mod comparisons;
pub mod github_installations;
pub mod oauth_connections;
pub mod personal_tokens;
pub mod project_build_counters;
pub mod projects;
pub mod screenshots;
pub mod tenant_members;
pub mod tenants;
pub mod users;
