//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "projects_tenant_id_slug_key")]
    pub tenant_id: Uuid,
    pub name: String,
    #[sea_orm(unique_key = "projects_tenant_id_slug_key")]
    pub slug: String,
    pub default_branch: String,
    /// 1 ピクセルを「差分あり」と判定する色距離のしきい値（0.0〜1.0）。
    #[sea_orm(column_type = "Double")]
    pub diff_threshold: f64,
    /// ビルドを失敗扱いにする差分ピクセル比率（0.0〜1.0、0.0 は「1px でも差分があれば失敗」）。
    #[sea_orm(column_type = "Double")]
    pub diff_ratio_fail: f64,
    /// GitHub App のインストール ID。Phase 6 で `github_installations` への FK にする。
    pub github_installation_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_repo: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "tenant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tenants: HasOne<super::tenants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
