//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "screenshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "screenshots_build_id_name_key")]
    pub build_id: Uuid,
    /// ビルド内で一意なスクリーンショット名（baseline との突合キー）。
    #[sea_orm(unique_key = "screenshots_build_id_name_key")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub width: i32,
    pub height: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "build_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub builds: HasOne<super::builds::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
