//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    /// この時刻より前に発行されたセッションを一括で無効化する（グローバルログアウト）。
    pub sessions_revoked_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub oauth_connections: HasMany<super::oauth_connections::Entity>,
    #[sea_orm(has_many)]
    pub personal_tokens: HasMany<super::personal_tokens::Entity>,
    #[sea_orm(has_many)]
    pub tenant_members: HasMany<super::tenant_members::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
