[package]
name = "handler"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
entity = { path = "../entity" }
job = { path = "../job" }
payload = { path = "../payload" }
service = { path = "../service" }
anyhow = { workspace = true }
apalis-postgres = { version = "1.0.0-rc.8", default-features = false, features = ["migrate", "tokio-comp", "time"] }
auth-core = { workspace = true }
axum = { workspace = true, features = ["multipart"] }
bytes = "1"
axum_session = { version = "0.20.0" }
axum_session_redispool = { version = "0.11.0" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
hex = { workspace = true }
hmac = { workspace = true }
reqwest = { workspace = true }
sea-orm = { workspace = true, features = ["with-chrono", "postgres-array"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
tower-http = { version = "0.7", features = ["limit"] }
utoipa-axum = "0.2.0"
uuid = { version = "1", features = ["serde"] }
validator = { workspace = true }
