/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthedGithubSetupRouteImport } from './routes/_authed/github.setup'
import { Route as AuthedSettingsLanguageRouteImport } from './routes/_authed/settings.language'
import { Route as AuthedSettingsTokensRouteImport } from './routes/_authed/settings.tokens'
import { Route as AuthedTTenantSlugIndexRouteImport } from './routes/_authed/t.$tenantSlug.index'
import { Route as AuthedTTenantSlugSettingsRouteImport } from './routes/_authed/t.$tenantSlug.settings'
import { Route as AuthedTTenantSlugPProjectSlugIndexRouteImport } from './routes/_authed/t.$tenantSlug.p.$projectSlug.index'
import { Route as AuthedTTenantSlugPProjectSlugBuildsNumberRouteImport } from './routes/_authed/t.$tenantSlug.p.$projectSlug.builds.$number'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedGithubSetupRoute = AuthedGithubSetupRouteImport.update({
  id: '/github/setup',
  path: '/github/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsLanguageRoute = AuthedSettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsTokensRoute = AuthedSettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTTenantSlugIndexRoute = AuthedTTenantSlugIndexRouteImport.update({
  id: '/t/$tenantSlug/',
  path: '/t/$tenantSlug/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTTenantSlugSettingsRoute =
  AuthedTTenantSlugSettingsRouteImport.update({
    id: '/t/$tenantSlug/settings',
    path: '/t/$tenantSlug/settings',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTTenantSlugPProjectSlugIndexRoute =
  AuthedTTenantSlugPProjectSlugIndexRouteImport.update({
    id: '/t/$tenantSlug/p/$projectSlug/',
    path: '/t/$tenantSlug/p/$projectSlug/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTTenantSlugPProjectSlugBuildsNumberRoute =
  AuthedTTenantSlugPProjectSlugBuildsNumberRouteImport.update({
    id: '/t/$tenantSlug/p/$projectSlug/builds/$number',
    path: '/t/$tenantSlug/p/$projectSlug/builds/$number',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/github/setup': typeof AuthedGithubSetupRoute
  '/settings/language': typeof AuthedSettingsLanguageRoute
  '/settings/tokens': typeof AuthedSettingsTokensRoute
  '/t/$tenantSlug/settings': typeof AuthedTTenantSlugSettingsRoute
  '/t/$tenantSlug/': typeof AuthedTTenantSlugIndexRoute
  '/t/$tenantSlug/p/$projectSlug/': typeof AuthedTTenantSlugPProjectSlugIndexRoute
  '/t/$tenantSlug/p/$projectSlug/builds/$number': typeof AuthedTTenantSlugPProjectSlugBuildsNumberRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AuthedIndexRoute
  '/github/setup': typeof AuthedGithubSetupRoute
  '/settings/language': typeof AuthedSettingsLanguageRoute
  '/settings/tokens': typeof AuthedSettingsTokensRoute
  '/t/$tenantSlug/settings': typeof AuthedTTenantSlugSettingsRoute
  '/t/$tenantSlug': typeof AuthedTTenantSlugIndexRoute
  '/t/$tenantSlug/p/$projectSlug': typeof AuthedTTenantSlugPProjectSlugIndexRoute
  '/t/$tenantSlug/p/$projectSlug/builds/$number': typeof AuthedTTenantSlugPProjectSlugBuildsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/github/setup': typeof AuthedGithubSetupRoute
  '/_authed/settings/language': typeof AuthedSettingsLanguageRoute
  '/_authed/settings/tokens': typeof AuthedSettingsTokensRoute
  '/_authed/t/$tenantSlug/settings': typeof AuthedTTenantSlugSettingsRoute
  '/_authed/t/$tenantSlug/': typeof AuthedTTenantSlugIndexRoute
  '/_authed/t/$tenantSlug/p/$projectSlug/': typeof AuthedTTenantSlugPProjectSlugIndexRoute
  '/_authed/t/$tenantSlug/p/$projectSlug/builds/$number': typeof AuthedTTenantSlugPProjectSlugBuildsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/$'
    | '/github/setup'
    | '/settings/language'
    | '/settings/tokens'
    | '/t/$tenantSlug/settings'
    | '/t/$tenantSlug/'
    | '/t/$tenantSlug/p/$projectSlug/'
    | '/t/$tenantSlug/p/$projectSlug/builds/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/$'
    | '/'
    | '/github/setup'
    | '/settings/language'
    | '/settings/tokens'
    | '/t/$tenantSlug/settings'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/p/$projectSlug'
    | '/t/$tenantSlug/p/$projectSlug/builds/$number'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/api/$'
    | '/_authed/'
    | '/_authed/github/setup'
    | '/_authed/settings/language'
    | '/_authed/settings/tokens'
    | '/_authed/t/$tenantSlug/settings'
    | '/_authed/t/$tenantSlug/'
    | '/_authed/t/$tenantSlug/p/$projectSlug/'
    | '/_authed/t/$tenantSlug/p/$projectSlug/builds/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/github/setup': {
      id: '/_authed/github/setup'
      path: '/github/setup'
      fullPath: '/github/setup'
      preLoaderRoute: typeof AuthedGithubSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/language': {
      id: '/_authed/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AuthedSettingsLanguageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/tokens': {
      id: '/_authed/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthedSettingsTokensRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/t/$tenantSlug/': {
      id: '/_authed/t/$tenantSlug/'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug/'
      preLoaderRoute: typeof AuthedTTenantSlugIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/t/$tenantSlug/settings': {
      id: '/_authed/t/$tenantSlug/settings'
      path: '/t/$tenantSlug/settings'
      fullPath: '/t/$tenantSlug/settings'
      preLoaderRoute: typeof AuthedTTenantSlugSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/t/$tenantSlug/p/$projectSlug/': {
      id: '/_authed/t/$tenantSlug/p/$projectSlug/'
      path: '/t/$tenantSlug/p/$projectSlug'
      fullPath: '/t/$tenantSlug/p/$projectSlug/'
      preLoaderRoute: typeof AuthedTTenantSlugPProjectSlugIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/t/$tenantSlug/p/$projectSlug/builds/$number': {
      id: '/_authed/t/$tenantSlug/p/$projectSlug/builds/$number'
      path: '/t/$tenantSlug/p/$projectSlug/builds/$number'
      fullPath: '/t/$tenantSlug/p/$projectSlug/builds/$number'
      preLoaderRoute: typeof AuthedTTenantSlugPProjectSlugBuildsNumberRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedGithubSetupRoute: typeof AuthedGithubSetupRoute
  AuthedSettingsLanguageRoute: typeof AuthedSettingsLanguageRoute
  AuthedSettingsTokensRoute: typeof AuthedSettingsTokensRoute
  AuthedTTenantSlugSettingsRoute: typeof AuthedTTenantSlugSettingsRoute
  AuthedTTenantSlugIndexRoute: typeof AuthedTTenantSlugIndexRoute
  AuthedTTenantSlugPProjectSlugIndexRoute: typeof AuthedTTenantSlugPProjectSlugIndexRoute
  AuthedTTenantSlugPProjectSlugBuildsNumberRoute: typeof AuthedTTenantSlugPProjectSlugBuildsNumberRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedGithubSetupRoute: AuthedGithubSetupRoute,
  AuthedSettingsLanguageRoute: AuthedSettingsLanguageRoute,
  AuthedSettingsTokensRoute: AuthedSettingsTokensRoute,
  AuthedTTenantSlugSettingsRoute: AuthedTTenantSlugSettingsRoute,
  AuthedTTenantSlugIndexRoute: AuthedTTenantSlugIndexRoute,
  AuthedTTenantSlugPProjectSlugIndexRoute:
    AuthedTTenantSlugPProjectSlugIndexRoute,
  AuthedTTenantSlugPProjectSlugBuildsNumberRoute:
    AuthedTTenantSlugPProjectSlugBuildsNumberRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
